### ISSUE TITLE
Unable to resolve 'Microsoft.Extensions.Hosting (>= 5.0.0)' for 'net5.0'

### ISSUE THREAD

**Issue by kalanisanders** [Azure-Samples/api-management-schema-import#17]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> issue "dotnet restore" or "dotnet build" from api-management-schema-import\ApiManagementSchemaImport\Mi
  crosoft.Azure.ApiManagement.WsdlProcessor.App

### Any log messages given by the failure
>  error NU1100: Unable to resolve 'Microsoft.Extensions.Hosting (>= 5.0.0)' for 'net5.0'.

### Expected/desired behavior
> project should build

### OS and Version?
> Windows 10

### Versions
> 22H2

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by knash94** [comment]
I had the same issue, deleting the config file inside of `C:\Users\<username>\AppData\Roaming\NuGet` worked perfectly.

Source: https://stackoverflow.com/a/68284740

**Comment by kalanisanders** [comment]
Thanks. I went to try again and it just worked this time. ¯\_(ツ)_/¯
