### ISSUE TITLE
Legacy .NET version supported

### ISSUE THREAD

**Issue by umashankar337** [Azure-Samples/api-management-schema-import#19]
- [ ] feature request: Support latest .NET framework

### Expected/desired behavior
> Currently the solution supports very old .NET runtime i.e. .NET 5.0 which is already out of support.

### OS and Version?
> Windows 10.

### Mention any other details that might be useful
Can you upgrade the source code to be compatible with latest .NET versions e.g. .NET 6 or 7 ?
> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by krhub** [comment]
Is there any update on this?

**Comment by umashankar337** [comment]
@shinjiDev @maksimkim 
Do we have any update on this legacy issue ?

**Comment by felipementel** [comment]
@umashankar337 now we are running .NET version 8 at main branch!

**Comment by mikebudzynski** [comment]
.NET 8 is now supported!
